
services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    
  db_freeq:
    image: postgres:latest
    environment:
      POSTGRES_USER: fcastro
      POSTGRES_PASSWORD: freeq123
      POSTGRES_DB: freeq_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_freeq:/var/lib/postgresql/data
